services:
  app:
    build: .
    command:
      - /bin/sh
      - -c
      - |
        npx knex migrate:latest --knexfile dist/knex-cli/knexfile.js
        npx knex seed:run --knexfile dist/knex-cli/knexfile.js
        node dist/index.js
    depends_on:
        - db
    env_file: compose.app.env
    init: true
    ports:
      - "8080:8080"
  db:
    env_file: compose.db.env
    image: postgres:16.1
    ports:
      # expose to host system's 5433 in case you're already running one
      # (to app, it's still 5432)
      - "5433:5432"