AWSTemplateFormatVersion: "2010-09-09"
Description: Solarpunk Drifters - ACM certificate

Parameters:
  DomainName:
    Description: Domain name (must be registered on Route53 before deploying this stack)
    Type: String
  HostedZoneId:
    Description: HostedZoneId for the domain e.g. Z23ABC4XYZL05B
    Type: AWS::Route53::HostedZone::Id

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

Outputs:
  CertificateArn:
    Description: ACM certificate for domain name
    Value: !Ref Certificate
