AWSTemplateFormatVersion: "2010-09-09"
Description: Solarpunk Drifters - Main CFN Stack

Rules:
  OnlyUsEast1:
    Assertions:
      - Assert:
          Fn::Equals:
            - !Ref AWS::Region
            - us-east-1
        AssertDescription: |
          This template can only be deployed in the us-east-1 region.
          This is because the ACM Certificate must be created in us-east-1

Parameters:
  ContainerImageUrl:
    Type: String
    Description: |
      The url of a container image for the instances to run, eg 
      "012345678910.dkr.ecr.<region-name>.amazonaws.com/<repository-name>@sha256:94afd1f2e64d908bc90dbca0035a5b567EXAMPLE"
  DomainName:
    Description: Domain name (must be registered on Route53 before deploying this stack)
    Type: String
  Environment:
    Type: String
    Description: Name for the environment.
  HostedZoneId:
    Description: HostedZoneId for the domain e.g. Z23ABC4XYZL05B
    Type: String

Resources:
  # TODO: once stabilized, write more conservative delete/replace policies

  AcmCertificateStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: ./acm-certificate.yaml
      Parameters:
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId

  ApiServerStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: ./api-server.yaml
      Parameters:
        ContainerImageUrl: !Ref ContainerImageUrl
        EnvironmentPrefix: !Ref Environment
        PublicSubnet1Id: !GetAtt NetworkStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt NetworkStack.Outputs.PublicSubnet2Id
        PrivateSubnet1Id: !GetAtt NetworkStack.Outputs.PrivateSubnet1Id
        VpcId: !GetAtt NetworkStack.Outputs.VpcId

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: ./network.yaml

  WebsiteStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: ./website.yaml
      Parameters:
        CertificateArn: !GetAtt AcmCertificateStack.Outputs.CertificateArn
        EnvironmentPrefix: !Ref Environment
        DomainName: !Ref DomainName
        ApiLoadBalancerDnsName: !GetAtt ApiServerStack.Outputs.ApiLoadBalancerDnsName

Outputs:
  CloudFrontDistributionId:
    Description: The ID of the CloudFront distribution of this stack
    Value: !GetAtt WebsiteStack.Outputs.CloudFrontDistributionId
  CloudFrontDistributionDomain:
    Description: The domain of the CloudFront distribution of this stack
    Value: !GetAtt WebsiteStack.Outputs.CloudFrontDistributionDomain
  StaticWebsiteS3BucketRoot:
    Description: Static website S3 bucket
    Value: !GetAtt WebsiteStack.Outputs.StaticWebsiteS3BucketRoot
  StaticWebsiteS3BucketRootArn:
    Description: Website bucket locator
    Value: !GetAtt WebsiteStack.Outputs.StaticWebsiteS3BucketRootArn
