AWSTemplateFormatVersion: "2010-09-09"
Description: Solarpunk Drifters - Secure static website on S3 served by CloudFormation

Resources:
  StaticWebsiteS3BucketLogs:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  StaticWebsiteS3BucketRoot:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref StaticWebsiteS3BucketLogs
        LogFilePrefix: "static-website-bucket/"

Outputs:
  StaticWebsiteS3BucketRootName:
    Description: Static website S3 bucket
    Value: !Ref StaticWebsiteS3BucketRoot
  StaticWebsiteS3BucketRootDomainName:
    Description: Domain name of root bucket
    Value: !GetAtt StaticWebsiteS3BucketRoot.DomainName
  StaticWebsiteS3BucketRootArn:
    Description: Website bucket locator
    Value: !GetAtt StaticWebsiteS3BucketRoot.Arn
  StaticWebsiteS3BucketLogs:
    Description: Logging bucket
    Value: !Ref StaticWebsiteS3BucketLogs
  StaticWebsiteS3BucketLogsDomainName:
    Description: Logging bucket Name
    Value: !GetAtt StaticWebsiteS3BucketLogs.DomainName
