# Build and test the api-server, including tests against a DB

name: api-server test

on:
  push:
    branches: ["main"]
    paths:
      - api-server/**
      - common/**
  pull_request:
    branches: ["main"]
    paths:
      - api-server/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./api-server
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run build
        working-directory: ./common
      - run: npm run build
        working-directory: ./api-server
      - run: npm test # run only unit tests
        working-directory: ./api-server
      # TODO: run db integration tests
