name: Lint CloudFormation templates

on:
  push:
    branches: [main]
    paths:
      - infrastructure/templates/*
      - infrastructure/lint/*
  pull_request:
    branches: [main]
    paths:
      - infrastructure/templates/*
      - infrastructure/lint/*
  workflow_dispatch:

jobs:
  lint-cfn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "infrastructure/lint/requirements.txt"
      - run: pip install -r infrastructure/lint/requirements.txt
      - run: pip install cfn-lint
      # Ignore W3002 because templates/main.yaml is designed to use "cloudformation package"
      - run: cfn-lint -i W3002 -t infrastructure/templates/*
