name: Monorepo test build and deploy

on:
  push:
    branches: [main]
    paths:
      - api-server/**
      - common/**
      - website/**
      - package*.json
  pull_request:
    branches: [main]
    paths:
      - api-server/**
      - common/**
      - website/**
      - package*.json
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  install-check-lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      # NOTE: building at least common/ is necessary for the tests
      - run: npm run build
      - run: npm run check
      - run: npm run lint
      - run: npm run test
      # TODO: run db integration tests
      # - run: npm run test-db-integration
      #   working-directory: ./api-server
      #   changed-files: ./api-server
      #
      - name: upload website artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-dist
          path: ./website/dist
          if-no-files-found: error
          # TODO: set repository-level default?
          retention-days: 1
      - name: upload api-server artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-server-dist
          path: api-server/dist
          # TODO: set repository-level default?
          retention-days: 1

  deploy-website:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: install-check-lint-test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: download website artifact
        uses: actions/download-artifact@v4
        with:
          name: website-dist
          path: website/dist
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.AWS_GH_OIDC_ROLE }}
          role-session-name: deploy-testing-website
          aws-region: ${{ vars.AWS_REGION }}
      - name: deploy website to testing bucket
        run: ./infrastructure/deploy-website-to-testing-bucket.sh ${{ vars.MAIN_STACK_NAME }}

  push-api-server:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: install-check-lint-test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: download api-server artifact
        uses: actions/download-artifact@v4
        with:
          name: api-server-dist
          path: api-server/dist
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.AWS_GH_OIDC_ROLE }}
          role-session-name: push-api-server-container
          aws-region: ${{ vars.AWS_REGION }}
      - name: login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Get ECR repository URL
        run: |
          echo "REPOSITORY=$(\
            ./infrastructure/get-ecr-uri.sh ${{ vars.MAIN_STACK_NAME }})" \
          >> "$GITHUB_ENV"
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build . -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f ./api-server/Dockerfile
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  # TODO: update latent ECS to use new image via CFN parameter
