# Lint, type-check, and test the website

name: website lint, type-check, and test

on:
  push:
    branches: ["main"]
    paths:
      - website/**
  pull_request:
    branches: ["main"]
    paths:
      - website/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./website
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - run: npm run lint
        working-directory: ./website
      - run: npm run check
        working-directory: ./website
      - run: npm run test
        working-directory: ./website
